name: Publish to npm

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: npm
      url: https://www.npmjs.com/package/opencode-claude-tailguard
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - run: bun install --frozen-lockfile
      - run: bun lint
      - run: bun tsc
      - run: |
          mkdir -p $HOME/.local/share/opencode
          bun test
      - id: publish
        continue-on-error: true
        run: |
          # 1.2.3, 1.2.3-alpha.0, ...
          VERSION=$(jq -r '.version' package.json)
          # alpha, beta, latest, ...
          TAG=$(echo "$VERSION" | grep -oE 'alpha|beta' || echo "latest")
          bun publish --tag $TAG  --access public

      - uses: actions/setup-node@v6
        if: steps.publish.outcome == 'failure'
        with:
          node-version: "latest"
      - if: steps.publish.outcome == 'failure'
        run: |
          # 1.2.3, 1.2.3-alpha.0, ...
          VERSION=$(jq -r '.version' package.json)
          # alpha, beta, latest, ...
          TAG=$(echo "$VERSION" | grep -oE 'alpha|beta' || echo "latest")
          npm publish --tag=$TAG --access public
